### ISSUE TITLE
Finetune on 30B LLaMA

### ISSUE THREAD

**Issue by Awyshw** [bofenghuang/vigogne#10]
When I use torchrun to finetune on A100 2node * 8 GPUs, OOM will appear.
Can you release your params?

**Comment by bofenghuang** [comment]
Hi @Awyshw,

It's in the [README](https://github.com/bofenghuang/vigogne#fine-tuning-llama-30b-model). I used 2 RTX8000 of 46Gb

**Comment by bofenghuang** [comment]
May be https://github.com/tloen/alpaca-lora/pull/361 ?
