### ISSUE TITLE
proposition d'un jeu d'instruction pour inclusion dans Vigogne

### ISSUE THREAD

**Issue by particitae** [bofenghuang/vigogne#26]
Bonjour
voici une proposition d'un court jeu d'instructions pour inclusion dans vos expériences fort interessantes.

https://gitlab.math.unistra.fr/miti-gt-donnees/gt-doremiti-instructions

il s'agit d'un jeu d'instruction autour des données scientifiques issu de la FAQ crée par le groupe de travail Données des Réseaux de la MiTi et disponible à cette adresse https://gt-atelier-donnees.miti.cnrs.fr/faq.html, le tout sous licence Creative Commons By.

cordialement
le GT DOREMIT

**Comment by bofenghuang** [comment]
Bonjour,

Désolé pour le délai de ma réponse. Merci pour votre proposition ! Le fichier est disponible dans le [data](https://github.com/bofenghuang/vigogne/blob/main/data/instruct/gt_doremiti_instructions.jsonl).

**Comment by particitae** [comment]
Super !!!
je l'ai déplacé sur HugginFace pour plus de facilité
https://huggingface.co/datasets/Gt-Doremiti/gt-doremiti-instructions

le dataset évoluera prochainement

**Comment by bofenghuang** [comment]
Merci ! J'ai ajouté un lien vers votre jeu de données dans la [documentation](https://github.com/bofenghuang/vigogne/blob/main/docs/data.md#data-collection). Si vous souhaitez apporter des modifications ou ajouter d'autres jeux de données, n'hésitez pas à créer un PR.
