### ISSUE TITLE
Can't load tokenizer

### ISSUE THREAD

**Issue by XReyRobert** [bofenghuang/vigogne#3]
Thanks for sharing,
it seems that pointing to the llama model doesn't work.
Is it looking for a specific folder organisation ?  tokenizer / Config.json files in the model directory ?

models/7B
├── checklist.chk
├── consolidated.00.pth
├── consolidated.01.pth
├── consolidated.02.pth
├── consolidated.03.pth
├── consolidated.04.pth
├── consolidated.05.pth
├── consolidated.06.pth
├── consolidated.07.pth
├── ggml-model-f16.bin
├── ggml-model-q4.bin
└── params.json

OSError: Can't load tokenizer for './models/7B'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './models/7B' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

**Comment by bofenghuang** [comment]
Hi @XReyRobert,

Thanks for your interest!

It seems like that the error message came from the step that combines the LLaMA model with Vigogne-LoRA weights using `export_state_dict_checkpoint.py`? The `base_model_name_or_path` parameter should point to a name or a local path that includes the LLaMA model files in Hugging Face's format. I will update the REAME to clarify this!
