### ISSUE TITLE
RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400

### ISSUE THREAD

**Issue by S0mbr3** [bofenghuang/vigogne#4]
I am getting the RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400 after trying to combine vigogne weights with llama 13B and 30B huggingface models converted. it does work well with the 7B.

And here the RuntimeError from the 30B model -> RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 44302336

Here is the command used to combine weights: 

python ../scripts/export_state_dict_checkpoint.py \  
    --base_model_name_or_path "../../llama-13b-hf" \
    --lora_model_name_or_path "bofenghuang/vigogne-lora-13b" \
    --output_dir ./models/13B

**Comment by bofenghuang** [comment]
Hi @S0mbr3 !

Thanks for pointing this out!

Just pushed the modif which adds config for other checkpoints. Now you can run with:

```bash
python ../scripts/export_state_dict_checkpoint.py \
    --base_model_name_or_path "../../llama-13b-hf" \
    --lora_model_name_or_path "bofenghuang/vigogne-lora-13b" \
    --output_dir ./models/13B \
    --checkpoint_size "13b"
```
