### ISSUE TITLE
A bit lost

### ISSUE THREAD

**Issue by DARDORKE** [bofenghuang/vigogne#6]
Hi !

I followed the google colab process to create the vigogne lora model but now I don't understand how to use it. I did it on 13B model and I exported the file on my local storage.
Now to use it, do I have to convert and combine this file or can I use it in llama.cpp ?
What extension should this file have ?

Thank you !

**Comment by bofenghuang** [comment]
Hi @DARDORKE !

Thanks for playing with the model!

What extension do your current file have? If you want to infer the model using GPU, you can use the [Colab Notebook](https://colab.research.google.com/github/bofenghuang/vigogne/blob/main/infer.ipynb). If you want to try it on your PC, you can quantize the combined model and deploy with llama.cpp, refer to [this section](https://github.com/bofenghuang/vigogne#try-it-out-on-your-own-pc).

**Comment by DARDORKE** [comment]
Thanks for the anwser.

My current file has no extension.

I used google collab to generate model by using this code :

`from peft import PeftModel
from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-30b-hf")
model = LlamaForCausalLM.from_pretrained(
    "decapoda-research/llama-30b-hf",
    load_in_8bit=True,
    device_map="auto",
)
model = PeftModel.from_pretrained(model, "bofenghuang/vigogne-lora-30b")

path = "/content/drive/My Drive/my-model/"

if not os.path.exists(path):
    os.makedirs(path)

torch.save(model.state_dict(), os.path.join(path, "vigogne-lora-30b"))`

I just modified https://colab.research.google.com/github/bofenghuang/vigogne/blob/main/infer.ipynb to extract generated model to my Drive. I got a 12Go file (13B) without extension.

Now i'd like to try it on my PC, so I just have to quantize this file and deploy with llama.cpp?

Thank you

**Comment by bofenghuang** [comment]
If you want to try it on your PC, you can just refer to [this section](https://github.com/bofenghuang/vigogne#try-it-out-on-your-own-pc). There is a step-by-step guide.

**Comment by amirouche** [comment]
> If you want to try it on your PC, you can just refer to [this section](https://github.com/bofenghuang/vigogne#try-it-out-on-your-own-pc). There is a step-by-step guide.

I still do not understand how it works. What is this argument:

```
    --lora_model_name_or_path "bofenghuang/vigogne-lora-7b" \
```

Thanks in advance

**Comment by bofenghuang** [comment]
Hi @amirouche, you can think of it as a patch of the original LLaMA model to get the fine-tuned instruction following vigogne model.
