### ISSUE TITLE
Automatic translation 

### ISSUE THREAD

**Issue by xerexesx** [bofenghuang/vigogne#7]
Thanks for the code but the model has been translated in automatic without taking into account some aspects.
Example all that concerns the programming languages.
In python on a loop the model returns the translation of the functions.
for i in range(1,11):
    print i

this back to me:
pour i dans gamme(1,11):
    imprime i

No way to change this ?

**Comment by clementvp** [comment]
Maybe tweak the dataset with coding parts and retrain ?

**Comment by bofenghuang** [comment]
Hi @xerexesx @clementvp ,

Just updated the dataset to improve the quality.

It may still contain some affected tasks. PRs are welcome to help improve the quality of this dataset!

**Comment by coco875** [comment]
hmm a thing you can do is to use the original model to manipulate code and if you have comment or other thing you want in french you can translate by vigogne.
